### ISSUE TITLE
Cannot find module 'inert'

### ISSUE THREAD

**Issue by postblue** [electerious/ackee-server#1]
Just testing a bit Ackee v2. Got this:

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'inert'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/postblue/Projets/Ackee/server/lib/main.js:11:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by electerious** [comment]
Thanks for letting me know :) Should be fixed now, but there isn't much to test, yet. UI and documentation is still missing.

**Comment by postblue** [comment]
You're welcome. :) If there isn't much to test, testing will be done in no time! ;)
